export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_DETAIL_POKEMON = "GET_DETAIL_POKEMON";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const FILTER_TYPE = "FILTER_TYPE"
export const ORDER_NAME ="ORDER_NAME";
export const ORDER_ATTACK = "ORDER_ATTACK";
export const FILTER_POKEMONS = "FILTER_POKEMONS";